name: CI/CD

on:
  push:
    branches: [ "main" ]
#    branches: [ "main" , "action" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-war:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -e package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  build-docker:
    needs: build-war

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . -t  message-server:$(date +%s) -f Dockerfile
#        run: docker build -f --file Dockerfile --tag message-server:$(date +%s) .
#      run: docker build --tag=message-server:latest .