name: Maven Package

on:
  push:
    branches: [ "main" , "action" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jar_version: 1.0.0

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Bump jar version
        id: bump
#        run: |
#          POMPATH=my-app
#          OLD_VERSION=$(cd $POMPATH && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
#          BUMP_MODE="none"
#          old="$OLD_VERSION"
#          parts=( ${old//./ } )
#          bv=$((parts[2] + 1))
#          NEW_VERSION="${parts[0]}.${parts[1]}.${bv}"
#          echo "pom.xml at" $POMPATH "will be bumped from" $OLD_VERSION "to" $NEW_VERSION
#          mvn -q versions:set -DnewVersion="${NEW_VERSION}" --file $POMPATH/pom.xml
#          echo ::set-output name=jar_version::${NEW_VERSION}

      - name: Compile
#        run: mvn -B compile --file my-app/pom.xml
        run: mvn -B compile --file pom.xml

      - name: Build a package
#        run: mvn -B package --file my-app/pom.xml
        run: mvn -B package --file pom.xml

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: ${{ github.workspace }}/target/*.jar
#          path: ${{ github.workspace }}/my-app/target/*.jar
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: jar-artifact
          path: target/
      - name: Docker build
        run: |
#          docker build . -t shayki/shayki-maven:${{needs.build.outputs.jar_version}}
          docker build . -t  message-server:$(date +%s)

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Docker push
#        run: |
#          docker push shayki/shayki-maven:${{needs.build.outputs.jar_version}}
#  run:
#    runs-on: ubuntu-18.04
#    needs: [build, deploy]
#
#    steps:
#      - name: Run container
#        run: |
#          docker run shayki/shayki-maven:${{needs.build.outputs.jar_version}}